project_id = "zeafrtcerafgyisnaizw"

[functions.create-user]
verify_jwt = false

[functions.update-user-email]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false