// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Detect session from URL hash only once (faster initial load)
    detectSessionInUrl: true,
  },
  global: {
    // Reuse Keep-Alive connections — reduces TCP handshake overhead
    fetch: (url, options = {}) =>
      fetch(url, { ...options, keepalive: true }),
  },
  db: {
    // Use the pooler schema if available (reduces per-query connection cost)
    schema: 'public',
  },
  realtime: {
    // Increase heartbeat interval — reduces background traffic
    params: { eventsPerSecond: 2 },
  },
});